title: openSPDM Documentation
description: Documentation for openSPDM project
#url: "https://openspdm.com"
#remote_theme: alexander-heimbuch/millidocs
remote_theme: just-the-docs/just-the-docs


#markdown: kramdown
#kramdown:
#  syntax_highlighter_opts:
#    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

---
