title: openSPDM Documentation
description: Documentation for openSPDM project
#url: "https://openspdm.com"
#remote_theme: alexander-heimbuch/millidocs
theme: just-the-docs

#markdown: kramdown
#kramdown:
#  syntax_highlighter_opts:
#    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
#  - README.md

---
